export const APP_CONFIG_SEED_KEYS = [
  'GLM_API_KEY',
  'GLM_ENDPOINT',
  'GLM_GLOBAL_CONCURRENCY',
  'GLM_GLOBAL_MIN_INTERVAL_MS',
  'GLM_GLOBAL_RATE_LIMIT_COOLDOWN_MS',
  'GLM_GLOBAL_RATE_LIMIT_MAX_MS',
  'GLM_ASR_CONCURRENCY',
  'GLM_ASR_MIN_INTERVAL_MS',
  'GLM_ASR_RATE_LIMIT_COOLDOWN_MS',
  'GLM_ASR_RATE_LIMIT_MAX_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_CONCURRENCY',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_MIN_INTERVAL_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_RATE_LIMIT_COOLDOWN_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_RATE_LIMIT_MAX_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_CONCURRENCY',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_MIN_INTERVAL_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_RATE_LIMIT_COOLDOWN_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_RATE_LIMIT_MAX_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_CONCURRENCY',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_MIN_INTERVAL_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_RATE_LIMIT_COOLDOWN_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_RATE_LIMIT_MAX_MS',
  'GLM_TRANSCRIPT_ANALYSIS_CONCURRENCY',
  'GLM_TRANSCRIPT_ANALYSIS_MIN_INTERVAL_MS',
  'GLM_TRANSCRIPT_ANALYSIS_RATE_LIMIT_COOLDOWN_MS',
  'GLM_TRANSCRIPT_ANALYSIS_RATE_LIMIT_MAX_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_MODEL',
  'GLM_TRANSCRIPT_SEGMENT_TRANSLATION_MODEL',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_MAX_TOKENS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_BUMP_MAX_TOKENS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_JSON_MODE',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_RETRY_MAX',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_RETRY_BASE_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_RETRY_MAX_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_DEGRADE_ON_STRICT_FAIL',
  'GLM_TRANSCRIPT_SUMMARY_MODEL',
  'GLM_TRANSCRIPT_SUMMARY_MAX_TOKENS',
  'GLM_TRANSCRIPT_SUMMARY_THINKING',
  'GLM_TRANSCRIPT_SEGMENT_ANALYSIS_THINKING',
  'GLM_TRANSCRIPT_SUMMARY_RETRY_MAX',
  'GLM_TRANSCRIPT_SUMMARY_RETRY_BASE_MS',
  'GLM_TRANSCRIPT_SUMMARY_RETRY_MAX_MS',
  'TRANSCRIPT_EVENTS_SEGMENT_INTERVAL_MS',
  'TRANSCRIPT_EVENTS_SEGMENT_CHUNK_SIZE',
  'TRANSCRIPT_EVENTS_SEGMENT_WINDOW_EVENTS',
  'TRANSCRIPT_EVENTS_SEGMENT_TRIGGER_ON_STOP_TRANSCRIBE',
  'TRANSCRIPT_EVENTS_SEGMENT_SYSTEM_PROMPT',
  'TRANSCRIPT_EVENTS_SEGMENT_STRICT_SYSTEM_PROMPT',
  'TRANSCRIPT_EVENTS_SEGMENT_MAX_SEGMENTS_PER_RUN',
  'TRANSCRIPT_EVENTS_SEGMENT_MAX_IN_FLIGHT',
  'TRANSCRIPT_EVENTS_SEGMENT_MAX_PENDING_SESSIONS',
  'TRANSCRIPT_EVENTS_SEGMENT_MAX_STALENESS_MS',
  'TRANSCRIPT_AUTO_SPLIT_GAP_MS',
  'TRANSCRIPT_DEBUG_LOG_UTTERANCES',
  'APP_LOG_REQUEST_RESPONSE_ENABLED',
  'APP_LOG_ERROR_ENABLED',
  'APP_LOG_SYSTEM_ENABLED',
  'TRANSCRIPT_SEGMENT_TRANSLATION_ENABLED',
  'TRANSCRIPT_SEGMENT_TRANSLATION_LANGUAGE',
  'TRANSCRIPT_ANALYSIS_LANGUAGE_ENABLED',
  'TRANSCRIPT_ANALYSIS_LANGUAGE',
  'TRANSCRIPT_ANALYSIS_SUMMARY_SYSTEM_PROMPT',
  'TRANSCRIPT_ANALYSIS_CHUNK_SUMMARY_SYSTEM_PROMPT',
  'TRANSCRIPT_ANALYSIS_SEGMENT_SYSTEM_PROMPT',
  'TRANSCRIPT_MAX_BUFFER_DURATION_SOFT_MS',
  'TRANSCRIPT_MAX_BUFFER_DURATION_HARD_MS',
] as const

export const APP_CONFIG_SECURITY_PASSWORD_KEY = 'SYSTEM_SECURITY_PASSWORD_HASH'

export type AppConfigSeedKey = typeof APP_CONFIG_SEED_KEYS[number]

export const APP_CONFIG_REMARKS: Record<AppConfigSeedKey, string> = {
  GLM_API_KEY: 'GLM 平台 API Key，用于所有 GLM 请求鉴权（敏感信息，建议仅在可信环境配置）。',
  GLM_ENDPOINT: 'GLM Chat Completions 接口地址（http/https）。',
  GLM_GLOBAL_CONCURRENCY: '全局 GLM 并发上限：所有 GLM 请求共享同一个队列/限流器。',
  GLM_GLOBAL_MIN_INTERVAL_MS: '全局 GLM 启动请求最小间隔（ms），用于控制 QPS（0 表示不做间隔限制）。',
  GLM_GLOBAL_RATE_LIMIT_COOLDOWN_MS: '遇到 429 后的全局冷却时间（ms），冷却期间会延后调度请求。',
  GLM_GLOBAL_RATE_LIMIT_MAX_MS: '全局冷却时间上限（ms），用于限制指数退避的最大延迟。',
  GLM_ASR_CONCURRENCY: 'ASR 模块专用 GLM 并发上限；未配置时回退全局并发上限。',
  GLM_ASR_MIN_INTERVAL_MS: 'ASR 模块专用 GLM 启动请求最小间隔（ms）；未配置时回退全局间隔。',
  GLM_ASR_RATE_LIMIT_COOLDOWN_MS: 'ASR 模块专用 429 冷却时间（ms）；未配置时回退全局冷却。',
  GLM_ASR_RATE_LIMIT_MAX_MS: 'ASR 模块专用 429 冷却上限（ms）；未配置时回退全局冷却上限。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_CONCURRENCY:
    '语句拆分模块专用 GLM 并发上限；未配置时回退全局并发上限。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_MIN_INTERVAL_MS:
    '语句拆分模块专用 GLM 启动请求最小间隔（ms）；未配置时回退全局间隔。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_RATE_LIMIT_COOLDOWN_MS:
    '语句拆分模块专用 429 冷却时间（ms）；未配置时回退全局冷却。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_RATE_LIMIT_MAX_MS:
    '语句拆分模块专用 429 冷却上限（ms）；未配置时回退全局冷却上限。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_CONCURRENCY:
    '语句重建拆分模块专用 GLM 并发上限；未配置时回退全局并发上限。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_MIN_INTERVAL_MS:
    '语句重建拆分模块专用 GLM 启动请求最小间隔（ms）；未配置时回退全局间隔。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_RATE_LIMIT_COOLDOWN_MS:
    '语句重建拆分模块专用 429 冷却时间（ms）；未配置时回退全局冷却。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_RATE_LIMIT_MAX_MS:
    '语句重建拆分模块专用 429 冷却上限（ms）；未配置时回退全局冷却上限。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_CONCURRENCY:
    '语句翻译模块专用 GLM 并发上限；未配置时回退全局并发上限。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_MIN_INTERVAL_MS:
    '语句翻译模块专用 GLM 启动请求最小间隔（ms）；未配置时回退全局间隔。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_RATE_LIMIT_COOLDOWN_MS:
    '语句翻译模块专用 429 冷却时间（ms）；未配置时回退全局冷却。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_RATE_LIMIT_MAX_MS:
    '语句翻译模块专用 429 冷却上限（ms）；未配置时回退全局冷却上限。',
  GLM_TRANSCRIPT_ANALYSIS_CONCURRENCY: 'AI 分析模块专用 GLM 并发上限；未配置时回退全局并发上限。',
  GLM_TRANSCRIPT_ANALYSIS_MIN_INTERVAL_MS:
    'AI 分析模块专用 GLM 启动请求最小间隔（ms）；未配置时回退全局间隔。',
  GLM_TRANSCRIPT_ANALYSIS_RATE_LIMIT_COOLDOWN_MS:
    'AI 分析模块专用 429 冷却时间（ms）；未配置时回退全局冷却。',
  GLM_TRANSCRIPT_ANALYSIS_RATE_LIMIT_MAX_MS:
    'AI 分析模块专用 429 冷却上限（ms）；未配置时回退全局冷却上限。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_MODEL: '语句拆分任务使用的 GLM 模型名称；为空会导致语句拆分不可用。',
  GLM_TRANSCRIPT_SEGMENT_TRANSLATION_MODEL:
    '语句翻译任务使用的 GLM 模型名称；为空时回退语句拆分模型。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_MAX_TOKENS: '语句拆分：单次请求的 max_tokens 上限（影响输出长度与成本）。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_BUMP_MAX_TOKENS:
    '语句拆分：当 finish_reason=length（截断）时，二次请求提升 max_tokens 的目标值。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_JSON_MODE:
    '语句拆分：是否启用 JSON 模式（response_format=json_object），用于提升结构化输出稳定性。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_RETRY_MAX: '语句拆分：遇到 429 的最大重试次数（0 表示不重试）。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_RETRY_BASE_MS: '语句拆分：429 退避基准延迟（ms）。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_RETRY_MAX_MS: '语句拆分：429 退避最大延迟（ms）。',
  GLM_TRANSCRIPT_EVENT_SEGMENT_DEGRADE_ON_STRICT_FAIL:
    '语句拆分：严格 JSON 解析/校验失败时是否允许降级为原始 extractedText（减少失败率但可能降低一致性）。',
  GLM_TRANSCRIPT_SUMMARY_MODEL:
    '会议总结模型；不配置时会回退使用语句拆分模型（GLM_TRANSCRIPT_EVENT_SEGMENT_MODEL）。',
  GLM_TRANSCRIPT_SUMMARY_MAX_TOKENS: '会议总结：单次输出 max_tokens 上限。',
  GLM_TRANSCRIPT_SUMMARY_THINKING: '会议总结：是否启用深度思考（可能提升质量但更慢/更贵）。',
  GLM_TRANSCRIPT_SEGMENT_ANALYSIS_THINKING:
    '针对性分析：是否启用深度思考（未配置时沿用会议总结设置）。',
  GLM_TRANSCRIPT_SUMMARY_RETRY_MAX: '会议总结：遇到 429 的最大重试次数（0 表示不重试）。',
  GLM_TRANSCRIPT_SUMMARY_RETRY_BASE_MS: '会议总结：429 退避基准延迟（ms）。',
  GLM_TRANSCRIPT_SUMMARY_RETRY_MAX_MS: '会议总结：429 退避最大延迟（ms）。',
  TRANSCRIPT_EVENTS_SEGMENT_INTERVAL_MS:
    '语句拆分触发间隔（ms，去抖/合并窗口）；0 表示每次事件更新都尝试拆分。',
  TRANSCRIPT_EVENTS_SEGMENT_CHUNK_SIZE:
    '语句拆分上下文窗口事件数（CHUNK_SIZE）：取尾部 N 条事件作为 LLM 上下文。',
  TRANSCRIPT_EVENTS_SEGMENT_WINDOW_EVENTS:
    '语句拆分上下文窗口事件数（历史兼容字段 WINDOW_EVENTS）；建议使用 CHUNK_SIZE。',
  TRANSCRIPT_EVENTS_SEGMENT_TRIGGER_ON_STOP_TRANSCRIBE:
    '收到 stop_transcribe 时是否立即触发一次语句拆分。',
  TRANSCRIPT_EVENTS_SEGMENT_SYSTEM_PROMPT: '语句拆分：系统提示词（system prompt）。',
  TRANSCRIPT_EVENTS_SEGMENT_STRICT_SYSTEM_PROMPT:
    '语句拆分：严格回显提示词（用于约束/回显 JSON 输出的提示词）。',
  TRANSCRIPT_EVENTS_SEGMENT_MAX_SEGMENTS_PER_RUN:
    '单次语句拆分任务最多生成段数（用于限制一次运行的处理量）。',
  TRANSCRIPT_EVENTS_SEGMENT_MAX_IN_FLIGHT:
    '语句拆分：全局并发上限（同时处理的会话数），避免大量任务挂起占用资源。',
  TRANSCRIPT_EVENTS_SEGMENT_MAX_PENDING_SESSIONS:
    '语句拆分：待处理会话的最大数量（超过会丢弃最旧会话以防堆积）。',
  TRANSCRIPT_EVENTS_SEGMENT_MAX_STALENESS_MS:
    '语句拆分：待处理任务的最大滞留时间（ms，超过将丢弃）。',
  TRANSCRIPT_AUTO_SPLIT_GAP_MS:
    '实时转写：无 segmentKey 时，相邻 utterance 更新超过该间隔（ms）将强制切分为新 speech。',
  TRANSCRIPT_DEBUG_LOG_UTTERANCES: '转写调试：打印最终 utterance / event（仅用于排障，建议关闭）。',
  APP_LOG_REQUEST_RESPONSE_ENABLED: '日志记录：是否记录请求与回复（仅用于排障，建议关闭）。',
  APP_LOG_ERROR_ENABLED: '日志记录：是否记录错误日志（仅用于排障，建议关闭）。',
  APP_LOG_SYSTEM_ENABLED: '日志记录：是否记录系统日志（仅用于排障，建议关闭）。',
  TRANSCRIPT_SEGMENT_TRANSLATION_ENABLED:
    '语句翻译：是否在语句拆分后生成翻译（保留技术名/标识符）。',
  TRANSCRIPT_SEGMENT_TRANSLATION_LANGUAGE:
    '语句翻译：翻译目标语言（如“简体中文”“English”），用于控制翻译输出语言。',
  TRANSCRIPT_ANALYSIS_LANGUAGE_ENABLED:
    'AI 分析：是否强制输出指定语言结果（关闭则不强制输出语言）。',
  TRANSCRIPT_ANALYSIS_LANGUAGE:
    'AI 分析：输出目标语言（如“简体中文”“English”）。',
  TRANSCRIPT_ANALYSIS_SUMMARY_SYSTEM_PROMPT:
    'AI 分析：会议总结系统提示词（影响总体总结风格与结构）。',
  TRANSCRIPT_ANALYSIS_CHUNK_SUMMARY_SYSTEM_PROMPT:
    'AI 分析：分片总结系统提示词（用于长会话拆分提炼）。',
  TRANSCRIPT_ANALYSIS_SEGMENT_SYSTEM_PROMPT:
    'AI 分析：针对性分析系统提示词（用于单句/单段分析）。',
  TRANSCRIPT_MAX_BUFFER_DURATION_SOFT_MS:
    'SmartAudioBuffer：软上限（ms），满足“有静音”条件时触发 flush。',
  TRANSCRIPT_MAX_BUFFER_DURATION_HARD_MS:
    'SmartAudioBuffer：硬上限（ms），无静音也会强制 flush；必须 >= 软上限。',
}

export const APP_CONFIG_FIELDS = [
  {
    field: 'glmApiKey',
    key: 'GLM_API_KEY',
    type: 'string',
    defaultValue: '',
  },
  {
    field: 'glmEndpoint',
    key: 'GLM_ENDPOINT',
    type: 'string',
    defaultValue: 'https://open.bigmodel.cn/api/paas/v4/chat/completions',
  },
  {
    field: 'glmGlobalConcurrency',
    key: 'GLM_GLOBAL_CONCURRENCY',
    type: 'number',
    defaultValue: 1,
    min: 1,
    max: 50,
  },
  {
    field: 'glmGlobalMinIntervalMs',
    key: 'GLM_GLOBAL_MIN_INTERVAL_MS',
    type: 'number',
    defaultValue: 500,
    min: 0,
    max: 60000,
  },
  {
    field: 'glmGlobalRateLimitCooldownMs',
    key: 'GLM_GLOBAL_RATE_LIMIT_COOLDOWN_MS',
    type: 'number',
    defaultValue: 2000,
    min: 0,
    max: 120000,
  },
  {
    field: 'glmGlobalRateLimitMaxMs',
    key: 'GLM_GLOBAL_RATE_LIMIT_MAX_MS',
    type: 'number',
    defaultValue: 15000,
    min: 0,
    max: 300000,
  },
  {
    field: 'glmAsrConcurrency',
    key: 'GLM_ASR_CONCURRENCY',
    type: 'number',
    defaultValue: 1,
    min: 1,
    max: 50,
  },
  {
    field: 'glmAsrMinIntervalMs',
    key: 'GLM_ASR_MIN_INTERVAL_MS',
    type: 'number',
    defaultValue: 500,
    min: 0,
    max: 60000,
  },
  {
    field: 'glmAsrRateLimitCooldownMs',
    key: 'GLM_ASR_RATE_LIMIT_COOLDOWN_MS',
    type: 'number',
    defaultValue: 2000,
    min: 0,
    max: 120000,
  },
  {
    field: 'glmAsrRateLimitMaxMs',
    key: 'GLM_ASR_RATE_LIMIT_MAX_MS',
    type: 'number',
    defaultValue: 15000,
    min: 0,
    max: 300000,
  },
  {
    field: 'glmTranscriptEventSegmentConcurrency',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_CONCURRENCY',
    type: 'number',
    defaultValue: 1,
    min: 1,
    max: 50,
  },
  {
    field: 'glmTranscriptEventSegmentRebuildConcurrency',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_CONCURRENCY',
    type: 'number',
    defaultValue: 1,
    min: 1,
    max: 50,
  },
  {
    field: 'glmTranscriptEventSegmentMinIntervalMs',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_MIN_INTERVAL_MS',
    type: 'number',
    defaultValue: 500,
    min: 0,
    max: 60000,
  },
  {
    field: 'glmTranscriptEventSegmentRebuildMinIntervalMs',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_MIN_INTERVAL_MS',
    type: 'number',
    defaultValue: 500,
    min: 0,
    max: 60000,
  },
  {
    field: 'glmTranscriptEventSegmentRateLimitCooldownMs',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_RATE_LIMIT_COOLDOWN_MS',
    type: 'number',
    defaultValue: 2000,
    min: 0,
    max: 120000,
  },
  {
    field: 'glmTranscriptEventSegmentRebuildRateLimitCooldownMs',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_RATE_LIMIT_COOLDOWN_MS',
    type: 'number',
    defaultValue: 2000,
    min: 0,
    max: 120000,
  },
  {
    field: 'glmTranscriptEventSegmentRateLimitMaxMs',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_RATE_LIMIT_MAX_MS',
    type: 'number',
    defaultValue: 15000,
    min: 0,
    max: 300000,
  },
  {
    field: 'glmTranscriptEventSegmentRebuildRateLimitMaxMs',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_REBUILD_RATE_LIMIT_MAX_MS',
    type: 'number',
    defaultValue: 15000,
    min: 0,
    max: 300000,
  },
  {
    field: 'glmTranscriptEventSegmentTranslationConcurrency',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_CONCURRENCY',
    type: 'number',
    defaultValue: 1,
    min: 1,
    max: 50,
  },
  {
    field: 'glmTranscriptEventSegmentTranslationMinIntervalMs',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_MIN_INTERVAL_MS',
    type: 'number',
    defaultValue: 500,
    min: 0,
    max: 60000,
  },
  {
    field: 'glmTranscriptEventSegmentTranslationRateLimitCooldownMs',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_RATE_LIMIT_COOLDOWN_MS',
    type: 'number',
    defaultValue: 2000,
    min: 0,
    max: 120000,
  },
  {
    field: 'glmTranscriptEventSegmentTranslationRateLimitMaxMs',
    key: 'GLM_TRANSCRIPT_EVENT_SEGMENT_TRANSLATION_RATE_LIMIT_MAX_MS',
    type: 'number',
    defaultValue: 15000,
    min: 0,
    max: 300000,
  },
  {
    field: 'glmTranscriptAnalysisConcurrency',
    key: 'GLM_TRANSCRIPT_ANALYSIS_CONCURRENCY',
    type: 'number',
    defaultValue: 1,
    min: 1,
    max: 50,
  },
  {
    field: 'glmTranscriptAnalysisMinIntervalMs',
    key: 'GLM_TRANSCRIPT_ANALYSIS_MIN_INTERVAL_MS',
    type: 'number',
    defaultValue: 500,
    min: 0,
    max: 60000,
  },
  {
    field: 'glmTranscriptAnalysisRateLimitCooldownMs',
    key: 'GLM_TRANSCRIPT_ANALYSIS_RATE_LIMIT_COOLDOWN_MS',
    type: 'number',
    defaultValue: 2000,
    min: 0,
    max: 120000,
  },
  {
    field: 'glmTranscriptAnalysisRateLimitMaxMs',
    key: 'GLM_TRANSCRIPT_ANALYSIS_RATE_LIMIT_MAX_MS',
    type: 'number',
    defaultValue: 15000,
    min: 0,
    max: 300000,
  },
  {
    field: 'transcriptEventsSegmentMaxInFlight',
    key: 'TRANSCRIPT_EVENTS_SEGMENT_MAX_IN_FLIGHT',
    type: 'number',
    defaultValue: 2,
    min: 1,
    max: 50,
  },
  {
    field: 'transcriptEventsSegmentMaxPendingSessions',
    key: 'TRANSCRIPT_EVENTS_SEGMENT_MAX_PENDING_SESSIONS',
    type: 'number',
    defaultValue: 300,
    min: 1,
    max: 5000,
  },
  {
    field: 'transcriptEventsSegmentMaxStalenessMs',
    key: 'TRANSCRIPT_EVENTS_SEGMENT_MAX_STALENESS_MS',
    type: 'number',
    defaultValue: 20000,
    min: 1000,
    max: 300000,
  },
  {
    field: 'transcriptAutoSplitGapMs',
    key: 'TRANSCRIPT_AUTO_SPLIT_GAP_MS',
    type: 'number',
    defaultValue: 2500,
    min: 0,
    max: 600000,
  },
  {
    field: 'transcriptMaxBufferDurationSoftMs',
    key: 'TRANSCRIPT_MAX_BUFFER_DURATION_SOFT_MS',
    type: 'number',
    defaultValue: 30000,
    min: 5000,
    max: 59000,
  },
  {
    field: 'transcriptMaxBufferDurationHardMs',
    key: 'TRANSCRIPT_MAX_BUFFER_DURATION_HARD_MS',
    type: 'number',
    defaultValue: 50000,
    min: 5000,
    max: 59000,
  },
  {
    field: 'transcriptDebugLogUtterances',
    key: 'TRANSCRIPT_DEBUG_LOG_UTTERANCES',
    type: 'boolean',
    defaultValue: false,
  },
  {
    field: 'appLogRequestResponseEnabled',
    key: 'APP_LOG_REQUEST_RESPONSE_ENABLED',
    type: 'boolean',
    defaultValue: false,
  },
  {
    field: 'appLogErrorEnabled',
    key: 'APP_LOG_ERROR_ENABLED',
    type: 'boolean',
    defaultValue: false,
  },
  {
    field: 'appLogSystemEnabled',
    key: 'APP_LOG_SYSTEM_ENABLED',
    type: 'boolean',
    defaultValue: false,
  },
  {
    field: 'transcriptSegmentTranslationEnabled',
    key: 'TRANSCRIPT_SEGMENT_TRANSLATION_ENABLED',
    type: 'boolean',
    defaultValue: false,
  },
  {
    field: 'transcriptSegmentTranslationLanguage',
    key: 'TRANSCRIPT_SEGMENT_TRANSLATION_LANGUAGE',
    type: 'string',
    defaultValue: '简体中文',
  },
  {
    field: 'glmTranscriptSegmentTranslationModel',
    key: 'GLM_TRANSCRIPT_SEGMENT_TRANSLATION_MODEL',
    type: 'string',
    defaultValue: '',
  },
  {
    field: 'transcriptAnalysisLanguageEnabled',
    key: 'TRANSCRIPT_ANALYSIS_LANGUAGE_ENABLED',
    type: 'boolean',
    defaultValue: true,
  },
  {
    field: 'transcriptAnalysisLanguage',
    key: 'TRANSCRIPT_ANALYSIS_LANGUAGE',
    type: 'string',
    defaultValue: '简体中文',
  },
  {
    field: 'glmTranscriptSummaryModel',
    key: 'GLM_TRANSCRIPT_SUMMARY_MODEL',
    type: 'string',
    defaultValue: '',
  },
  {
    field: 'glmTranscriptSummaryMaxTokens',
    key: 'GLM_TRANSCRIPT_SUMMARY_MAX_TOKENS',
    type: 'number',
    defaultValue: 2500,
    min: 256,
    max: 8192,
  },
  {
    field: 'glmTranscriptSummaryThinking',
    key: 'GLM_TRANSCRIPT_SUMMARY_THINKING',
    type: 'boolean',
    defaultValue: true,
  },
  {
    field: 'glmTranscriptSegmentAnalysisThinking',
    key: 'GLM_TRANSCRIPT_SEGMENT_ANALYSIS_THINKING',
    type: 'boolean',
    defaultValue: true,
  },
  {
    field: 'glmTranscriptSummaryRetryMax',
    key: 'GLM_TRANSCRIPT_SUMMARY_RETRY_MAX',
    type: 'number',
    defaultValue: 3,
    min: 0,
    max: 10,
  },
  {
    field: 'glmTranscriptSummaryRetryBaseMs',
    key: 'GLM_TRANSCRIPT_SUMMARY_RETRY_BASE_MS',
    type: 'number',
    defaultValue: 500,
    min: 0,
    max: 60000,
  },
  {
    field: 'glmTranscriptSummaryRetryMaxMs',
    key: 'GLM_TRANSCRIPT_SUMMARY_RETRY_MAX_MS',
    type: 'number',
    defaultValue: 8000,
    min: 0,
    max: 120000,
  },
] as const

export type AppConfigField = typeof APP_CONFIG_FIELDS[number]['field']
export type AppConfigFieldConfig = typeof APP_CONFIG_FIELDS[number]
