export const APP_CONFIG_SEED_KEYS = [
  'GLM_API_KEY',
  'GLM_ENDPOINT',
  'GLM_GLOBAL_CONCURRENCY',
  'GLM_GLOBAL_MIN_INTERVAL_MS',
  'GLM_GLOBAL_RATE_LIMIT_COOLDOWN_MS',
  'GLM_GLOBAL_RATE_LIMIT_MAX_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_MODEL',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_MAX_TOKENS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_BUMP_MAX_TOKENS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_JSON_MODE',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_RETRY_MAX',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_RETRY_BASE_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_RETRY_MAX_MS',
  'GLM_TRANSCRIPT_EVENT_SEGMENT_DEGRADE_ON_STRICT_FAIL',
  'GLM_TRANSCRIPT_SUMMARY_MODEL',
  'GLM_TRANSCRIPT_SUMMARY_MAX_TOKENS',
  'GLM_TRANSCRIPT_SUMMARY_THINKING',
  'GLM_TRANSCRIPT_SUMMARY_RETRY_MAX',
  'GLM_TRANSCRIPT_SUMMARY_RETRY_BASE_MS',
  'GLM_TRANSCRIPT_SUMMARY_RETRY_MAX_MS',
  'TRANSCRIPT_EVENTS_SEGMENT_INTERVAL_MS',
  'TRANSCRIPT_EVENTS_SEGMENT_CHUNK_SIZE',
  'TRANSCRIPT_EVENTS_SEGMENT_WINDOW_EVENTS',
  'TRANSCRIPT_EVENTS_SEGMENT_TRIGGER_ON_STOP_TRANSCRIBE',
  'TRANSCRIPT_EVENTS_SEGMENT_SYSTEM_PROMPT',
  'TRANSCRIPT_EVENTS_SEGMENT_STRICT_SYSTEM_PROMPT',
  'TRANSCRIPT_EVENTS_SEGMENT_MAX_SEGMENTS_PER_RUN',
  'TRANSCRIPT_AUTO_SPLIT_GAP_MS',
  'TRANSCRIPT_DEBUG_LOG_UTTERANCES',
  'TRANSCRIPT_MAX_BUFFER_DURATION_SOFT_MS',
  'TRANSCRIPT_MAX_BUFFER_DURATION_HARD_MS',
] as const

export type AppConfigSeedKey = typeof APP_CONFIG_SEED_KEYS[number]

export const APP_CONFIG_FIELDS = [
  {
    field: 'glmApiKey',
    key: 'GLM_API_KEY',
    type: 'string',
    defaultValue: '',
  },
  {
    field: 'glmEndpoint',
    key: 'GLM_ENDPOINT',
    type: 'string',
    defaultValue: 'https://open.bigmodel.cn/api/paas/v4/chat/completions',
  },
  {
    field: 'glmGlobalConcurrency',
    key: 'GLM_GLOBAL_CONCURRENCY',
    type: 'number',
    defaultValue: 1,
    min: 1,
    max: 50,
  },
  {
    field: 'glmGlobalMinIntervalMs',
    key: 'GLM_GLOBAL_MIN_INTERVAL_MS',
    type: 'number',
    defaultValue: 500,
    min: 0,
    max: 60000,
  },
  {
    field: 'glmGlobalRateLimitCooldownMs',
    key: 'GLM_GLOBAL_RATE_LIMIT_COOLDOWN_MS',
    type: 'number',
    defaultValue: 2000,
    min: 0,
    max: 120000,
  },
  {
    field: 'glmGlobalRateLimitMaxMs',
    key: 'GLM_GLOBAL_RATE_LIMIT_MAX_MS',
    type: 'number',
    defaultValue: 15000,
    min: 0,
    max: 300000,
  },
  {
    field: 'glmTranscriptSummaryModel',
    key: 'GLM_TRANSCRIPT_SUMMARY_MODEL',
    type: 'string',
    defaultValue: '',
  },
  {
    field: 'glmTranscriptSummaryMaxTokens',
    key: 'GLM_TRANSCRIPT_SUMMARY_MAX_TOKENS',
    type: 'number',
    defaultValue: 2500,
    min: 256,
    max: 8192,
  },
  {
    field: 'glmTranscriptSummaryThinking',
    key: 'GLM_TRANSCRIPT_SUMMARY_THINKING',
    type: 'boolean',
    defaultValue: true,
  },
  {
    field: 'glmTranscriptSummaryRetryMax',
    key: 'GLM_TRANSCRIPT_SUMMARY_RETRY_MAX',
    type: 'number',
    defaultValue: 3,
    min: 0,
    max: 10,
  },
  {
    field: 'glmTranscriptSummaryRetryBaseMs',
    key: 'GLM_TRANSCRIPT_SUMMARY_RETRY_BASE_MS',
    type: 'number',
    defaultValue: 500,
    min: 0,
    max: 60000,
  },
  {
    field: 'glmTranscriptSummaryRetryMaxMs',
    key: 'GLM_TRANSCRIPT_SUMMARY_RETRY_MAX_MS',
    type: 'number',
    defaultValue: 8000,
    min: 0,
    max: 120000,
  },
] as const

export type AppConfigField = typeof APP_CONFIG_FIELDS[number]['field']
export type AppConfigFieldConfig = typeof APP_CONFIG_FIELDS[number]
